import mockRequest from "./mockAjax";
import request from "./request";
// export const reqWineWater = () => {return mockRequest.get("/wineWater")};
// export const reqTechnology = () => {return mockRequest.get("/technology")};
// export const reqWine= () => {return mockRequest.get("/wine")};
// export const reqIcon = () => {return mockRequest.get("/icon")};
export const reqWineWater = () => {return request.get("https://cdn.jsdelivr.net/gh/taolin011/wineApp@main/src/mock/categoryBywine.json")};
export const reqTechnology = () => {return request.get("https://cdn.jsdelivr.net/gh/taolin011/wineApp@main/src/mock/technology.json")};
export const reqWine= () => {return request.get("https://cdn.jsdelivr.net/gh/taolin011/wineApp@main/src/mock/wine.json")};
export const reqIcon = () => {return request.get("https://cdn.jsdelivr.net/gh/taolin011/wineApp@main/src/mock/icon.json")};